debug_mode: False
use_log: False
robot_id: 0

role_info:
    is_client: False
    id: 'edge-01'

network_info:
    ip: '127.0.0.1'

    target_info:
        ip: '127.0.0.1'

message_info:
    nav:
        is_tcp: True
        port: 10000
    lidar:
        is_tcp: True
        port: 11000
    traj:
        is_tcp: True
        port: 12000
